Pizza-Aux-Crevettes/R-Type

- .gitignore
add the .idea to the gitignore
> ADD: .idea to gitignore

- .github/workflows/Rtype-mirror.yml
add github action for merge in Epitech repos when we have a merge in main of the mirror repos
> ADD: github action

- .github/workflows/Rtype-deploy-mdbook.yml
add github action for deploy mdbook when merge in dev branch
> ADD: github action mdbook

- client/include/InputClient.hpp
- client/src/Client.cpp
- client/src/InputClient.cpp
- client/src/main.cpp
Adding management of user click on key
> ADD: manage user click

- game_engine/include/components/Animation.hpp
- game_engine/include/components/Bullet.hpp
- game_engine/include/components/Button.hpp
- game_engine/include/components/Collider.hpp
- game_engine/include/components/Color.hpp
- game_engine/include/components/Health.hpp
- game_engine/include/components/Input.hpp
- game_engine/include/components/Position.hpp
- game_engine/include/components/Renderable.hpp
- game_engine/include/components/Rigidbody.hpp
- game_engine/include/components/Sound.hpp
- game_engine/include/components/Sprite.hpp
- game_engine/include/components/Text.hpp
- game_engine/include/components/Texture.hpp
- game_engine/include/components/Velocity.hpp
> FIX: pragma once hpp file components

- README.md
Add README at the root of the project, explaining how to run the project
> ADD: README

- game_engine/include/components/Button.hpp
- game_engine/include/components/Collider.hpp
- game_engine/include/components/Color.hpp
- game_engine/include/components/Components.hpp
- game_engine/include/components/Rigidbody.hpp
- game_engine/include/components/Sound.hpp
- game_engine/include/components/Sprite.hpp
- game_engine/include/components/Text.hpp
- game_engine/include/components/Texture.hpp
- game_engine/src/components/Button.cpp
- game_engine/src/components/Color.cpp
- game_engine/src/components/Sprite.cpp
- game_engine/src/components/Text.cpp
> ADD: variables into components function

- game_engine/README.md
> FIX: readme into game engine

- client/include/Client.hpp
- client/src/Client.cpp
- game_engine/include/Entity.hpp
- game_engine/include/System.hpp
- game_engine/src/System.cpp
- network/include/component/player/PlayerManager.hpp
- network/include/component/room/Room.hpp
- network/include/component/room/RoomManager.hpp
- network/src/component/player/PlayerManager.cpp
- network/src/component/room/Room.cpp
- network/src/component/room/RoomManager.cpp
adding folder and files for menu and options
> ERT 89 Structure of menu

- game_engine/src/System.cpp
> FIX: link system

- client/src/protocol/Protocol.cpp
- game_engine/src/System.cpp
adding the connexion between serveur and client for player
> ADD: connexion to player

- client/include/menu/Menu.hpp
- client/include/menu/OptionMenu.hpp
- client/src/Client.cpp
- client/src/menu/Menu.cpp
- client/src/menu/OptionMenu.cpp
- game_engine/src/System.cpp
Create option menu in client.cpp instead of in menu.cpp
> FIX : option menu no longer resets

- client/src/EntityManager.cpp
- client/src/protocol/NetworkClient.cpp
- client/src/protocol/Protocol.cpp
- game_engine/src/System.cpp
- network/src/component/hotkey/HotkeysManager.cpp
- network/src/component/player/PlayerProtocol.cpp
- network/src/socket/UdpSocket.cpp
> ERT-125-Update-position-server

- client/src/menu/Menu.cpp
setting the size maximum for inputs to 15 characters
> ADD: size max 15

- game_engine/include/System.hpp
- game_engine/include/components/Text.hpp
- game_engine/src/components/Text.cpp
- game_engine/src/systems/TextSystem.cpp
- game_engine/src/systems/UpdateSystem.cpp
add update Text, TexSize and Texture
> ERT-123-Update-Text-Textures

- game_engine/src/systems/ShapeSystem.cpp
> ERT-133-Add-texture-rect-on-shape 

- client/include/Client.hpp
- client/include/menu/Menu.hpp
- client/include/util/getResponsiveValue.hpp
- client/src/Client.cpp
- client/src/EntityManager.cpp
- client/src/menu/Menu.cpp
- client/src/menu/OptionMenu.cpp
- client/src/protocol/Protocol.cpp
- client/src/util/getResponsiveValue.cpp
- game_engine/include/System.hpp
- game_engine/src/System.cpp
- game_engine/src/systems/ShapeSystem.cpp
- game_engine/src/systems/UpdateSystem.cpp
> FIX: resolve all conflicts with responsive branch

- client/include/Client.hpp
- client/src/Client.cpp
- client/src/menu/Menu.cpp
- client/src/network/protocol/Protocol.cpp
- game_engine/include/components/Sound.hpp
- game_engine/src/components/Sound.cpp
> ADD: sound component

- client/src/component/hotkey/HotkeysManager.cpp
Adding condition for presskey in menu
> ERT-142-Wen-use-key-in-menu-we-have-segfault

- client/src/Client.cpp
- client/src/main.cpp
- client/src/network/protocol/Protocol.cpp
adding a default ip to connect to server when the ip input is empty
> ADD: default ip when ip input is empty

- client/src/Client.cpp
adding default username for player if username input is empty
> ERT-147-setup-default-username

- README.md
> ERT-146-Add-submodule-on-Readme

- client/include/component/hotkey/HotkeysCodes.hpp
> ERT-151-fix-shoot

- client/include/menu/Menu.hpp
- client/src/Client.cpp
- client/src/menu/Menu.cpp
> FIX: position input menu

- client/include/menu/Menu.hpp
- client/src/menu/Menu.cpp
> ADD: exit button

- client/include/EntityManager.hpp
- client/src/Client.cpp
- client/src/EntityManager.cpp
- client/src/network/protocol/Protocol.cpp
> ERT-155-Player-name

- client/include/EntityManager.hpp
- client/src/EntityManager.cpp
- client/src/network/protocol/Protocol.cpp
change the color of the sprite for each new players
> ERT-159-animation-sprite

- client/include/component/hotkey/HotkeysManager.hpp
- client/src/Client.cpp
- client/src/component/hotkey/HotkeysManager.cpp
> ERT-169-set-auto-fire

- client/include/Client.hpp
- client/include/EntityManager.hpp
- client/src/Client.cpp
- client/src/EntityManager.cpp
- client/src/network/protocol/Protocol.cpp
Fix the crash when an entity is accessed after it has been deleted.
> ERT-172-fix-crash

- client/include/Client.hpp
- client/include/EntityManager.hpp
- client/src/Client.cpp
- client/src/EntityManager.cpp
adding the refactoring of client file
> ERT-170-refactoring-client

- client/src/Client.cpp
- client/src/menu/LoseMenu.cpp
- client/src/menu/WinMenu.cpp
> FIX: replace button by text

- client/include/Client.hpp
- client/include/EntityManager.hpp
- client/include/menu/LoseMenu.hpp
- client/src/Client.cpp
- client/src/EntityManager.cpp
- client/src/menu/LoseMenu.cpp
- client/src/network/protocol/Protocol.cpp
> ADD: game over menu when player died

- client/src/Client.cpp
- client/src/EntityManager.cpp
> ADD: lose and win music

- client/include/menu/OptionMenu.hpp
- client/src/menu/OptionMenu.cpp
Removed controller in Option Menu
> RM: controller
